services:
  - type: web
    name: flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OKTA_DOMAIN
        value: "dev-14162863.okta.com"
      - key: OKTA_CLIENT_ID
        sync: false
      - key: OKTA_CLIENT_SECRET
        sync: false
      - key: OKTA_REDIRECT_URI
        value: "https://okta-openai-demo.onrender.com/callback"
      - key: OKTA_ISSUER
        value: "https://dev-14162863.okta.com/oauth2/ausn1mvtp8e6ob1VV5d7"
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis-session
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis-session
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: redis-session
          property: password

  - type: redis
    name: redis-session
    ipAllowList: []
    plan: free